# Generated by Django 2.2 on 2021-05-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210523_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbers',
            name='numbers',
            field=models.TextField(verbose_name='Число'),
        ),
    ]
